name: Benchmarks

on:
  workflow_run:
    workflows: [ 'Tests' ]
    types: [completed]

jobs:
  benchmark:

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest' ]
        python: [ '3.9' ]

    runs-on: ${{ matrix.os }}

    name: benchmark - ${{ matrix.os }} - python ${{ matrix.python }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Run benchmarks
      run: tox -e benchmarks
