name: lint

on:
  - push
  - pull_request

jobs:
  build:

    name: 'lint'

    runs-on: 'ubuntu-latest'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Run checks
      run: tox -e lint
