name: Packages

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  python-packages:

    name: 'python packages'

    runs-on: 'ubuntu-latest'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel

    - name: Build source distribution and wheel package
      run: python setup.py sdist bdist_wheel

  linux-packages:

    strategy:
      fail-fast: false
      matrix:
        distro: [
            'centos7.7',
            'centos8.0',
            'debian9',
            'debian10',
            'fedora32',
            'opensuse.tumbleweed',
            'opensuse42.3',
            'opensuse15.0',
            'opensuse15.1',
            'opensuse15.2',
            'ubuntu17.04',
            'ubuntu17.10',
            'ubuntu18.04',
            'ubuntu20.04'
        ]

    name: ${{ matrix.distro }}

    runs-on: 'ubuntu-latest'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Define version
      id: version
      uses: jimschubert/query-tag-action@v1

    - name: Show version
      run: |
        echo 'Version: ${{steps.version.outputs.tag}}'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install packagecore cloudsmith-cli

    - name: Build package
      run: packagecore -p ${{ matrix.distro }} $(grep -Po "__version__ = '\K.[^']+" rainbow/__init__.py)
